import typing

class IOBase:
    def __enter__(self) -> "Self": ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...

class TextIOBase(IOBase):
    def read(self, size: typing.Optional[int]) -> str: ...
    def write(self, s: str) -> int: ...
    def close(self) -> None: ...

class StringIO(TextIOBase):
    def __init__(self, initial_value: str = "", newline: str = "\n") -> None: ...
    def getvalue(self) -> str: ...
